### ISSUE TITLE
Condensation of moist air on cold walls

### ISSUE THREAD

**Issue by nitinminocha** [NimaSam/phaseChangeHeatFoam#1]
![image](https://user-images.githubusercontent.com/20879227/60170567-50020680-9826-11e9-8eef-628be56eb4bf.png)
Hi Nimasam
Thanks for sharing this powerful solver in public. It is very helpful.
I am currently working on condensation of moist air rising from bottom to top over  smooth walls having different sub-cooled temperatures.  Please give your suggestions for how to solve this problem using your solver.

Thanks
Dr. Nitin Minocha

**Comment by NimaSam** [comment]
Dear Nitin
As you may noticed, in the solver two phases should be liquid and vapor, if you can consider the mixture of air and moisture as a vapor, then you can use the solver directly with minor change. You only need to consider the saturation temperature as a function not constant value!

 However, if the presence of air can not be ignored, then some serious changes should be done in code to consider the non-condensable gas (air) . look following reference:
https://www.tandfonline.com/doi/abs/10.1080/10407782.2015.1023143

Best regard

**Comment by nitinminocha** [comment]
Dear NimaSam
First of all thanks for your quick reply and sharing this paper. As per your suggestion, I will begin with Pure steam first and then proceed for moist air case. I have some doubts regarding the solver capability. Please tell me whether the solver can handle:
1) steam going from bottom to top (against the gravity)
2) different  temperatures on left and right side of wall which will lead to different condensate thickness
3) 3D geometry
4) wavy nature at higher film Re and turbulence
Do I need to test different surface tension or phase change models?

Thank You
Nitin

**Comment by nitinminocha** [comment]
Dear NimaSam
I tried to install the solver in OpenFOAM 2.3.0 but I am not able to overcome these errors listed in error file. I am able to resolve some by reading the previous posts. Please have a look and give your suggestions. If you have the newer version of your code for OpenFOAM 2.3.0 then please share.

Thank you
[Error_phasechangeheatfoam.txt](https://github.com/NimaSam/phaseChangeHeatFoam/files/3335813/Error_phasechangeheatfoam.txt)

**Comment by NimaSam** [comment]
> Dear NimaSam
> First of all thanks for your quick reply and sharing this paper. As per your suggestion, I will begin with Pure steam first and then proceed for moist air case. I have some doubts regarding the solver capability. Please tell me whether the solver can handle:
> 
>     1. steam going from bottom to top (against the gravity)
> 
>     2. different  temperatures on left and right side of wall which will lead to different condensate thickness
> 
>     3. 3D geometry
> 
>     4. wavy nature at higher film Re and turbulence
>        Do I need to test different surface tension or phase change models?
> 
> 
> Thank You
> Nitin

Hi
Yes to All your questions, however i didnot consider the effect of turbulence on energy equation, because all my studies were on the laminar zone, however it can easily be implemented.

**Comment by NimaSam** [comment]
> Dear NimaSam
> First of all thanks for your quick reply and sharing this paper. As per your suggestion, I will begin with Pure steam first and then proceed for moist air case. I have some doubts regarding the solver capability. Please tell me whether the solver can handle:
> 
>     1. steam going from bottom to top (against the gravity)
> 
>     2. different  temperatures on left and right side of wall which will lead to different condensate thickness
> 
>     3. 3D geometry
> 
>     4. wavy nature at higher film Re and turbulence
>        Do I need to test different surface tension or phase change models?
> 
> 
> Thank You
> Nitin

**Comment by NimaSam** [comment]
> Dear NimaSam
> I tried to install the solver in OpenFOAM 2.3.0 but I am not able to overcome these errors listed in error file. I am able to resolve some by reading the previous posts. Please have a look and give your suggestions. If you have the newer version of your code for OpenFOAM 2.3.0 then please share.
> 
> Thank you
> [Error_phasechangeheatfoam.txt](https://github.com/NimaSam/phaseChangeHeatFoam/files/3335813/Error_phasechangeheatfoam.txt)

ok,
about this error:
         smoothInterfaceProperties(const smoothInterfaceProperties&);
you can replace it with OpenFOAM own library:
         interfaceProperties
Also 
        fvc::ddtPhiCorr(rAU, rho, U, phi)
and 
      phaseChangeTwoPhaseMixture

has changed in OpenFOAM2.3 compared to OpenFOAM2.2

i recommend to use OpenFOAM2.2 to easily install and use solver and tutorials.

Best regards
